spring:
  application:
    name: ecom-basic-application
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/product-db
      auto-index-creation: true
server:
  port: 9090